# This workflow will build only the Verdict jars

name: Verdict main build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        java-version: [ 1.8 ]
        ocaml-version: [ 4.07.1 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GraphViz
      uses: kamiazya/setup-graphviz@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ matrix.os }}-maven-

    - name: Run Maven build
      run: mvn -B install -Dtycho.localArtifacts=ignore --file tools/pom.xml
      env:
        GraphVizPath: /usr/bin
